"""empty message

Revision ID: 28837cb95fff
Revises: 665654229ed9
Create Date: 2024-02-26 18:13:32.986614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28837cb95fff'
down_revision = '665654229ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
