"""empty message

Revision ID: 3115f25bc0cb
Revises: 9be3190dcb15
Create Date: 2024-03-20 15:05:28.367131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3115f25bc0cb'
down_revision = '9be3190dcb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('net_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_price', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
