"""Changed relationships

Revision ID: 393b0bc572ac
Revises: e7bbfeb03f7e
Create Date: 2024-04-12 17:00:10.533667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393b0bc572ac'
down_revision = 'e7bbfeb03f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_supplier_id", 'supplier', ['supplier_id'], ['supplier_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_supplier_id', type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
