"""empty message

Revision ID: 665654229ed9
Revises: aa506f072fad
Create Date: 2024-02-26 16:14:05.983544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665654229ed9'
down_revision = 'aa506f072fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ean_code', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('ean_code')

    # ### end Alembic commands ###
