"""Added data and serial number in products and supplier  model

Revision ID: 778cc6675bd5
Revises: f9f5e8ac2b7d
Create Date: 2024-04-15 18:06:02.704941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778cc6675bd5'
down_revision = 'f9f5e8ac2b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('serial_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_supplier_id', 'supplier', ['supplier_id'], ['supplier_id'])

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('serial_number')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('serial_number')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
