"""empty message

Revision ID: 9be3190dcb15
Revises: de75696a22e6
Create Date: 2024-02-26 18:22:19.007250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be3190dcb15'
down_revision = 'de75696a22e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('formatted_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formatted_date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
