"""ADDED FK IN MIGRATIONS SCRIPT

Revision ID: edc45b2a1b6e
Revises: 393b0bc572ac
Create Date: 2024-04-12 17:13:31.824967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc45b2a1b6e'
down_revision = '393b0bc572ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'supplier', ['supplier_id'], ['supplier_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
